### ISSUE TITLE
Footnotes/Sources wrong line break in smartphone view

### ISSUE THREAD

**Issue by Kibia** [romanzipp/GetBetter#13]
https://user-images.githubusercontent.com/19223119/137498385-6ddab319-5e5e-40f7-87c5-6f8ba0605141.mp4

![image](https://user-images.githubusercontent.com/19223119/137504846-4b11e449-91f3-49ba-8eab-c83c700156c4.png)
sometimes the linebreak in hyperlink works, when there is a '-'.

I think thats default behavior by the framework. Maybe i can find a workaround by forcing the linebreak.

**Comment by romanzipp** [comment]
Fixed, thanks!
