### ISSUE TITLE
Discord usernames

### ISSUE THREAD

**Issue by kanashiatisuto** [romanzipp/GetBetter#24]
Hallo
Mibbis & tamaaas Discord Usernamen auf die bei "Über uns" verwiesen wird, sind inzwischen wahrscheinlich auch anders.

**Comment by larswmh** [comment]
Hi @kanashiatisuto,

durch einen [Commit](https://github.com/romanzipp/GetBetter/commit/a2077e7a3a63dd674c8bbdb83e87c7590bd8955b) aus der letzten Woche ist das in diesem Issue genannte Problem behoben. Es werden nun die neuen Discord Usernames genannt.
