### ISSUE TITLE
Fehlerhafter Grafikverweis

### ISSUE THREAD

**Issue by Alefriedo** [romanzipp/GetBetter#30]
In der Kategorie Proteine auf der Unterseite Ernährung ([https://get-better.me/ernaehrung/#protein](https://get-better.me/ernaehrung/#protein)) ist ein Verweis zur Grafik fehlerhaft. 

Im Kapitel "Wofür brauchen wir Proteine?" führt der Link zu https://www.eufic.org/images/uploads/whats-in-food/protein-functions_de.png und man erhält einen Error 404. 

Der tatsächliche Link zur Grafik aus der Quelle 34 ist https://www.eufic.org/en/images/uploads/whats-in-food/protein-functions_de.png (nach der Top-Level-Domain ist noch ein Sprachkürzel).

**Comment by mbrucker-kiel** [comment]
@romanzipp  eigentlich kann dieses issue auch geschlossen werden :)!
