### ISSUE TITLE
Grammatikfehler

### ISSUE THREAD

**Issue by thexcracmeister** [romanzipp/GetBetter#8]
Hey
Ich hab kaum erfahrung mit Github, also hoffe ihr nehmt mir meine Unwissenheit wie man hier mit dem Projekt umgehen soll nicht übel. 
Mir ist ein Grammatikfehler im Text Ernährung aufgefallen. 

> Vitamin B12
> Denkt daran, dass die angegebenen Daten, Informationen und Empfehlungen Durchschnittswerte sind. Alter, Krankheiten und besondere Umstände können erhebliche Abweichungen begünstigen. Bei Unsicherheiten wendet euch an den*die Ärzt*in eures Vertrauens.
> 
> Was ist B12?
> 
> Vitamin B12 ist ein Coenzym[^3] welches in Wechselwirkung mit dem Intrinsischen Faktor (einem Protein, welches unser Körper selbst produziert)[^4] unter anderem zur Blutbildung beiträgt und für ein funktionsfähiges Nervensystem sorgt.[^5] Menschen selbst können kein B12 herstellen, deshalb sind wir darauf angewiesen, B12 aus externen Quellen **zu uns nehmen.**[^6]

Hier im letzten Satz fehlt meiner Meinung nach ein zu. sollte heißen: ..., B12 aus externen Quellen zu uns **zu** nehmen. 

Bitte korrigiert mich wenn Grammatik/Rechtschreib Issues erwünscht sind oder nicht. 

mfg,
Martin Kargl

**Comment by romanzipp** [comment]
Hey, danke für den Hinweis! Ich habe den Fehler korrigiert. Ist komplett okay wenn du das als Issue hier meldest! 😊
